### ISSUE TITLE
Video not playing but showing info screen

### ISSUE THREAD

**Issue by dumbo0001** [aznhusband/aznhusband.github.io#17]
The add-on is not working anymore. Icdrama has been changed to block viewing the drama's from our add-on. Instead of playing the video an information is shown which states it isn't supported by the add-on anymore.

**Comment by dumbo0001** [comment]
@aznhusband This time it is not something that is easy to fix for me. I will need some time to figure how the new mechanism is working. Any help is welcome (also from other smart ppl).

**Comment by jkfoong** [comment]
Perhaps having a look on the site js can reveal the detecting mechanism of Icdrama?

**Comment by aznhusband** [comment]
Yeah, I was at it for about 3 hours last night.  I'll keep at it today.  My goal this time around is to actually learn how to use the inspector in Firefox, as opposed to my usual idiocy of playing around with wget.  This will take some time.

**Comment by fueltank34** [comment]
Look like this is stopping it
<a class="vb_closebtt" onclick="$('#vb_adplayer').empty();$('#vb_adplayer').hide();vb_autostart=1;jwplayer().play();">Close ad &amp; Play</a>

I'll try find the js

**Comment by fueltank34** [comment]
`<a class="vb_closebtt" onclick="$('#vb_adplayer').empty();$('#vb_adplayer').hide();vb_autostart=1;jwplayer().play();">Close ad &amp; Play</a>`

**Comment by aznhusband** [comment]
Well, we just need to find out what process the javascript goes through to ultimately deliver the link to the media.

**Comment by fueltank34** [comment]
Edited my message with what works for me.

**Comment by boleanly** [comment]
I looked in to this for a long while last night. The problem is because the wrong VB_TOKEN is being obtained. The new VB_TOKEN and VB_ID are generated from a script right after the old script where the add-on retrieves the Ajax POST data. You can test this by checking the current VB_TOKEN variable in the console, and the VB_TOKEN from the old method, a script named **video_id**.vbjs.html where **video_id** is the characters/name of the html file i.e. vb.icdrama.se/v/**video_id**.html. You can then resend the Ajax POST request with the old VB_TOKEN and decode the streams giving the current allrss.se videos. If you resend with the new VB_TOKEN, you'll get the streams.

Old script: <script type="text/javascript" src="/v/qpuxQsdW0hbem7bi7-t-CQ.vbjs.html">

If you look immediately after, they have a Javascript with somewhat procedural functions like this:

New new: <script>var I2FI={**##really long list/table of functions##**}</script>

I've looked through 7 - 8 videos, and the function that generates the VB_TOKEN is pretty much the same aside from a **key** and an **encrypted string**.

The function looks like this when beautified through JSBeautifier.org:

```
        wW: (function() {
            return {
                H: function(f) {
                    var R = '',
                        s = decodeURIComponent("%00%01%10%3C%06%7B%1D%3D7i%13%05%19*%3F%2F%18u%0A.2%1B%2FY%0F%14%18%2C%11%5D%00%1A%222%1D~8%1F%1B7%08%056%01%08%17%18K%06%04%09%2C%02u%1Ca4(%06t%0C%16%3A%1A%3Ai!%09%0E%0F2%1E%3B*%19%2Bzt%3B%3Eg%2F%08%5D%02%1D%2F%25e%0A%1F*(%15sg%10%198%3F%22B%14te5%11X%0C%186'7%1D9)%3F%3E%3F%5B%2B0%7F-%24%60!%3E87%2C");
                    for (var c = 0, r = 0; c < s.length; c++, r++) {
                        if (r === f.length) {
                            r = 0
                        }
                        R += String.fromCharCode(s.charCodeAt(c) ^ f.charCodeAt(r))
                    }
                    R = R.split('~|.');
                    return function(L) {
                        return R[L]
                    }
                }('ULQYK3')
            }
        })()
```

I think there's some readability trickery here because it can be simplified to this from my tests:

```
        wW: { H: function(f) {
                    var R = '',
                        s = decodeURIComponent("%00%01%10%3C%06%7B%1D%3D7i%13%05%19*%3F%2F%18u%0A.2%1B%2FY%0F%14%18%2C%11%5D%00%1A%222%1D~8%1F%1B7%08%056%01%08%17%18K%06%04%09%2C%02u%1Ca4(%06t%0C%16%3A%1A%3Ai!%09%0E%0F2%1E%3B*%19%2Bzt%3B%3Eg%2F%08%5D%02%1D%2F%25e%0A%1F*(%15sg%10%198%3F%22B%14te5%11X%0C%186'7%1D9)%3F%3E%3F%5B%2B0%7F-%24%60!%3E87%2C");
                    for (var c = 0, r = 0; c < s.length; c++, r++) {
                        if (r === f.length) {
                            r = 0
                        }
                        R += String.fromCharCode(s.charCodeAt(c) ^ f.charCodeAt(r))
                    }
                    R = R.split('~|.');
                    return function(L) {
                        return R[L]
                    }
                }('ULQYK3')
            }
```
Some other important bits:
```
        E6: function() {
            return typeof I2FI.wW.H === 'function' ? I2FI.wW.H.apply(I2FI.wW, arguments) : I2FI.wW.H;
        },
```
```
var C0, kM, _G, oQ;
C0 = I2FI.E6(0), _G = I2FI.E6(2), oQ = I2FI.jO(3), kM = I2FI.E6(1);
var VB_TOKEN = C0;
var VB_ID = kM; < /script>
```

The top function does some decryption/decoding to generate a string array R consisting of VB_TOKEN as R[0], VB_ID as R[1], and I think 'length' as R[2] and 'toString' as R[3] for some reason I don't know. The variable names R, s, f, c, r seems to stay the same so they could be used to capture this script. Although it might be better to just capture the decodeURIComponent() since it's unique in the HTML. The **key** I referred to is the default argument to function(f), which is 'ULQYK3' in this case. The **encrypted string** is the argument to decodeURIComponent(##encrypted string##).

The bottom two snippets is just further readability trickery that just defines VB_TOKEN as R[0] and VB_ID and R[1].

Sorry for the lengthy post. Just want to put all my findings down. Not sure if there are any other issues as I haven't tried to implement this yet because I'm not the most efficient Python coder. I'll try to write something that does the same thing as the above JavaScript function. Then I'll see if I can capture the encrypted string and the key in the main add-on and see if it works. I'm sure one of you guys can do it faster though. :D

**Comment by aznhusband** [comment]
K thanks, I'll start poking.  I'm still at work, so my hacking time is... furtive... at the moment :)

**Comment by dumbo0001** [comment]
Let me try first. If there is no PR in like 2 hours you can try it. The previous post was already helpful for the decoding.

**Comment by aznhusband** [comment]
Hmmmm, not for right now, but a consideration for going forward:

https://github.com/PiotrDabkowski/Js2Py

The dramanice plugin uses js2py to interpret javascript from the site... wonder if we could look at doing the same.

**Comment by dumbo0001** [comment]
@aznhusband didn't succeed in getting it to work. 

Using an online python interpreter I can get a correct resulting string, but not in the encoding. I think it is related with some encoding stuff (unicode etc). Python is not my expertise so I'll leave it for you now. 

You can find my changes in my branch: https://github.com/dumbo0001/aznhusband.github.io/tree/addon-fix. 

Good luck with the fix! Hope you can do it ;-)

**Comment by aznhusband** [comment]
Sweet, I'll pull from yours, and figure out the encoding.

**Comment by aznhusband** [comment]
Got it.  Upload coming shortly.  Thanks to dumbo0001, boleanly.  Will add boleanly to credits.

**Comment by aznhusband** [comment]
Also, will bump to 1.9.0

**Comment by dumbo0001** [comment]
Working now.. Let's see for how long it will last this time...

**Comment by boleanly** [comment]
Thanks! Working for me too. My parents would be happy to test it further :D
