### ISSUE TITLE
picasaweb seems to no longer be working

### ISSUE THREAD

**Issue by gumpwa** [aznhusband/aznhusband.github.io#41]
on the website the #2 360/720 seem to be working but not the original and not through kodi

**Comment by aznhusband** [comment]
Yes, I'll have to have a look over the weekend.

**Comment by xalagaco** [comment]
Picasaweb links are the only ones that ever work for me. I don't know if it's geolocation thing.
I've observed that whenever 1080p is in the list, none of the links play.
Since a couple of days ago, listings with 720p stopped working, mostly but not all.
Occasional shows that I have come across which list 360p only does seem to stream.

**Comment by aznhusband** [comment]
This weekend I'll look at moving us to ResolveURL, instead of URLResolver.  Hopefully that will fix the issue.

**Comment by aznhusband** [comment]
Moved to ResolveURL, fixed (hopefully) in 2.0.1

**Comment by gumpwa** [comment]
New release works great!  Thanks for the quick turnaround!
